urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.views.generic.simple import redirect_to
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from filebrowser.sites import site
from audio.teklif.views import OtomatikTeklif
from audio.dokuman.models import Dokuman
from audio.urun.models import Urun, Kategori
from audio.ortakVeri.sitemap import EkstraSitemap
from django.views.decorators.cache import never_cache

admin.autodiscover()

urun_dict = {
    'queryset': Urun.objects.all()
}

dokuman_dict = {
    'queryset': Dokuman.objects.all()
}    

kategori_dict = {
    'queryset': Kategori.objects.all()
}

sitemaps = {
    'duzsayfa': FlatPageSitemap,
    'kategori': GenericSitemap(kategori_dict),
    'urun': GenericSitemap(urun_dict),
    'dokuman': GenericSitemap(dokuman_dict),
    'diger': EkstraSitemap
}

urlpatterns = patterns('',
    url(r'^admin/filebrowser/', include(site.urls)),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^site_media/', redirect_to, {'url': None}),
    (r'^urunler/urun/', redirect_to, {'url': None}),
    (r'^turkish/', redirect_to, {'url': None}),
    (r'^english/', redirect_to, {'url': None}),
    (r'^urun', include('audio.urun.urls')),
    (r'^haber/', include('audio.haber.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^takip/', include('audio.bilgiTakip.urls')),
    (r'^teklif/', include('audio.teklif.urls')),
    (r'^teklif-istiyorum/', never_cache(OtomatikTeklif.as_view())),
    (r'^dokuman/', include('audio.dokuman.urls')),
    (r'^accounts/login/$','django.contrib.auth.views.login'),
    (r'^', include('audio.urun.urls')),
    (r'^', include('audio.calisanProfil.urls')),
    (r'^', include('audio.bilgiGiris.urls')), 
    (r'^', include('audio.ozelSayfa.urls')),
)

if settings.LOCAL:
    urlpatterns += patterns('',
         url(r'^static-development/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.PROJECT_PATH + '/statik',
        }),
        url(r'^statik/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.PROJECT_PATH + '/statikTasinmaz',
        }),
        ('^favicon.ico/$', redirect_to, {'url': 'http://s.aucdn.net/resim/favicon.ico'}),
   )

urun/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('audio.urun.views',
    (r'^sistemler/$', 'sistem'),
    (r'^/(?P<urun>[\w\-]+)/$', 'urun'),
    (r'^ler/(?P<kategori>[\w\-]+)/$','urunler'),
)

urun/models.py
# coding: utf-8
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.files.storage import default_storage
from filebrowser.fields import FileBrowseField
from audio.ortakVeri.sprite import sprite_generator
import os

SERI=(
     ("konsept","Konsept"),
     ("basic","Basic"),
     )

TIP =(
     ("goruntulu","Görüntülü"),
     ("sesli","Sesli"),
     )

class Sistem(models.Model):
    isim = models.CharField("Isim",max_length=200)
    tip = models.CharField("Tip", max_length = 50, choices =TIP)
    aciklama = models.TextField('Sistemin Aciklamasi')
    resim = FileBrowseField('Sistem Ikonu',max_length=150)
    sema = FileBrowseField('Sistemin Semasi',max_length=150,blank=True,null=True)
    class Meta: 
        verbose_name_plural = "Sistemler"
    def __unicode__(self):
        return unicode(self.isim)

class Ozellik(models.Model):
    isim = models.CharField("Aciklama", max_length = 200)
    class Meta:
        verbose_name_plural = "Ozellikler"
    def __unicode__(self):
        return unicode(self.isim)

class Kategori(models.Model):
    isim = models.CharField("Isim", max_length=50)
    slug = models.SlugField("Duzlestirilmis Isim", max_length = 50)
    class Meta:
        verbose_name_plural = "Kategoriler"
    def __unicode__(self):
        return unicode(self.isim)
    def get_absolute_url(self):
        return '/urunler/' + self.slug

class Urun(models.Model):
    isim = models.CharField("Isim", max_length=50)
    resim = FileBrowseField('Urunun Resmi', max_length=200) 
    sistem = models.ManyToManyField(Sistem,blank=True,null=True)
    kategori = models.ForeignKey(Kategori, related_name="UrunKategori", verbose_name="Kategori")
    seri = models.CharField("Seri",max_length=10,choices=SERI,blank=True,null=True)
    resim_yazi = models.CharField("Resim Alti Yazisi",max_length=200,blank=True,null=True)
    tanitim = models.TextField("Tanitim Metni",blank=True,null=True)
    ozellik = models.ManyToManyField(Ozellik, blank= True, null=True, related_name = "UrunOzellikler")
    slug = models.SlugField('Duzlestirilmis Isim')
    panel = models.ManyToManyField('self',blank=True,null=True)
    yeni = models.BooleanField('Yeni Urun, Anasayfada Gosterilsin',blank=True)
    class Meta:
        verbose_name_plural = "Urunler"
    def __unicode__(self):
        return self.isim
    def get_absolute_url(self):
        return '/urun/' + self.slug

class DigerModel(models.Model):
    urun = models.ForeignKey(Urun)
    resim = FileBrowseField('Diger Modelin Resmi',max_length=200)
    aciklama = models.CharField("Diger Modelin Aciklamasi",max_length=100)
    class Meta:
        verbose_name_plural = 'Diger Modeller'
    def __unicode__(self):
        return unicode(self.aciklama)

@receiver(post_save, sender=Sistem)
def sistem_sprite(sender, **kwargs):
    pic_sistem = [sistem.resim for sistem in Sistem.objects.all()]
    pic_ver = [pic.version_generate('sistem_ufak') for pic in pic_sistem]
    sprite_generator('systems', pic_ver)

@receiver(post_save, sender=Urun)
def urun_sprite(sender, **kwargs):
    instance = kwargs['instance']
    if instance.yeni == True:
        pic_urun = [urun.resim for urun in Urun.objects.filter(yeni=True)]
        pic_ver = [pic.version_generate('yeni_ufak') for pic in pic_urun]
        sprite_generator('products', pic_ver)
    if 'panel' in instance.kategori.isim:
        pic_urun = [urun.resim for urun in Urun.objects.filter(
            kategori__isim__contains='panel')]
        pic_ver = [pic.version_generate('panel_ufak') for pic in pic_urun]
        sprite_generator('panels', pic_ver)

urun/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from audio.urun.models import Urun, Kategori, Sistem
from audio.dokuman.models import Dokuman
from django.template import RequestContext

def sistem(request):
    goruntulu = Sistem.objects.filter(tip='goruntulu')
    sesli = Sistem.objects.filter(tip='sesli')
    return render_to_response('sistem.html',{'goruntulu':goruntulu,'sesli':sesli},context_instance=RequestContext(request)) 

def urun(request,urun):
    istenenUrun = get_object_or_404(Urun, slug=urun)
    dokuman = Dokuman.objects.filter(urun_sayfa=True)
    if not 'panel' in istenenUrun.kategori.isim:
        panelKonsept = istenenUrun.panel.filter(seri='konsept')
        panelBasic = istenenUrun.panel.filter(seri='basic')
    else:
        panelKonsept, panelBasic = [], []
    return render_to_response('urun.html',{'urun':istenenUrun, 'dokuman':dokuman, 'panelBasic':panelBasic,'panelKonsept':panelKonsept},context_instance=RequestContext(request))

def urunler(request,kategori):
    kategori_db = get_object_or_404(Kategori, slug=kategori)
    istenenKategori = kategori_db.UrunKategori.all()
    konsept = istenenKategori.filter(seri='konsept')
    basic = istenenKategori.filter(seri='basic')
    ortak = istenenKategori.filter(seri=None)
    return render_to_response('kategori.html',{'baslik': kategori_db.isim,'konsept':konsept, 'basic':basic, 'ortak':ortak},context_instance=RequestContext(request))

urun/templates/kategori.html
{% extends 'taban.html' %}

{% block baslik %}{{ baslik|title }} - Audio Elektronik{% endblock %}
{% block aciklama %}{{ baslik|title }}, bu ürünlerle binanızda şık bir şekilde dahili iletişim yapabilirsiniz.{% endblock %}
{% block icerik %}
<!--KONSEPT-->
{% if konsept %}
{% if basic or ortak %}
{% include "kategori_liste.html" with sira=2 sira_grid=28 sira_grid_inner=26 sira_grid_push=1 seri='konsept' urun_listesi=konsept %}
{% else %}
{% include "kategori_liste.html" with sira=1 sira_grid=56 sira_grid_inner=52 sira_grid_push=2 seri='konsept' urun_listesi=konsept %}
{% endif %} 
{% endif %}

<!--BASIC-->
{% if basic %}
{% if konsept or ortak %}
{% include "kategori_liste.html" with sira=2 sira_grid=28 sira_grid_inner=26 sira_grid_push=1 seri='basic' urun_listesi=basic %}
{% else %}
{% include "kategori_liste.html" with sira=1 sira_grid=56 sira_grid_inner=52 sira_grid_push=2 seri='basic' urun_listesi=basic %}
{% endif %} 
{% endif %}

{% if basic and konsept %}
<div class="clear"></div>
{% endif %}

<!--ORTAK-->
{% if ortak %}
{% if basic and konsept or not konsept and not basic %}
{% include "kategori_liste.html" with sira=1 sira_grid=56 sira_grid_inner=52 sira_grid_push=2 seri='ortak' urun_listesi=ortak %}
{% else %}
{% include "kategori_liste.html" with sira=2 sira_grid=28 sira_grid_inner=26 sira_grid_push=1 seri='ortak' urun_listesi=ortak %}
{% endif %}
{% endif %}
<div class="clear"></div>
{% endblock %}

urun/templates/kategori_liste.html
{% load fb_versions %}
<div class="grid_{{ sira_grid  }}">
 <div class="grid_{{ sira_grid }} sprites sprites-{% if sira == 2 %}yarim{% else %}tam{% endif %}_ust-png"></div>
 <div class="grid_{{ sira_grid }} {% if sira == 1 %}one{% else %}two{% endif %}">
  <div class="grid_{{ sira_grid_inner }} push_{{ sira_grid_push }}">
   <div class="grid_{{ sira_grid_inner }} centered">
    {% if seri == 'ortak' %}
        <div class='topd'></div>
    {% else %}
        <img src="{{ STATIC_CODE }}resim/{{ seri }}.jpg"/>
    {% endif %}
   </div>
   {% for urun in urun_listesi %}
   {% if sira == 2 %}
   {% cycle '<div class="grid_26">' '' %}
   {% else %}
   {% cycle '<div class="grid_52">' '' '' '' %}
   {% endif %}
   <div class="grid_13 {% if sira == 1 %}{% cycle 'alpha' '' '' 'omega' %}{% else %}{% cycle 'alpha' 'omega' %}{% endif %} centered">
    <div class="grid_13 topd"></div>
    <div class="grid_13">
     <a href='/urun/{{ urun.slug }}'><img src="{% version urun.resim.path 'urun_ufak' %}"/></a>
    </div>
    <div class="grid_13" style='margin-top:10px;'><a href='/urun/{{ urun.slug }}' style='text-decoration:none;color:black;'>{{ urun.isim }}</a></div>
   </div> 
   {% if sira == 2%}
   {% cycle '' '</div>' %}
   {% else %}
   {% cycle '' '' '' '</div>' %}
   {% endif %}
   {% endfor %}
   {% if not urun_listesi.count|divisibleby:'2' or sira != 2 and urun_listesi.count == 2 %}</div>{% endif %}
  </div>
 </div>
 <div class="grid_{{ sira_grid }} sprites sprites-{% if sira == 2 %}yarim{% else %}tam{% endif %}_alt-png"></div>
</div>

urun/templates/panel_liste.html
{% load fb_versions %}
{% load ortakVeri %}
<div class="grid_12 alpha">
 <div class="grid_12 centered"><img src="{{ STATIC_CODE }}resim/{{ seri }}.jpg"/></div>
 <div class="grid_12 centered">
  {% for p in panel %}
  <a href='/urun/{{ p.slug }}' style="margin-right:4px;">
   <img src="{% version p.resim.path 'panel_ufak' %}"/>
  </a>
  {% endfor %}
 </div>
 <div class="grid_11 push_1">
  <div class="grid_11 topd"></div>
  <strong style='text-transform:capitalize'>{{ seri }} serisi paneller</strong>
  {% for p in panel %}
  <div class="grid_11">- {{ p.isim }}</div>
  {% endfor %}
 </div> 
</div>

urun/templates/sistem.html
{% extends 'taban.html' %}

{% block baslik %}Sesli ve Görüntülü Sistemler - Audio Elektronik{% endblock %}
{% block aciklama %}Sistemler görüntülü yada görüntüsüz ünitelerinizin kabiliyetlerini ve kurulum için gerekli altyapıyı belirler. Audio' nun her türlü ihtiyaç için sistemi vardir.{% endblock %}

{% block icerik %}
{% include 'tekli_ac.html' %}
  <div class="grid_52 push_2">
   <div class="grid_52">
    <h2>Sistemler</h2>
   </div>
   {% include 'sistem_liste.html' with tip='Görüntülü' sistemler=goruntulu class='alpha' %}
   {% include 'sistem_liste.html' with tip='Sesli' sistemler=sesli class='omega' %}
  </div>
{% include 'tekli_kapat.html' with clear=True %}
{% endblock %}

urun/templates/sistem_liste.html
{% load fb_versions %}
<div class="grid_26 {{ class }}">
 <div class='grid_26'>
  <strong>{{ tip }} Sistemler</strong>
 </div>
 <div class='grid_26' style='height:10px'></div>
 {% for sistem in sistemler %}
 <div class="grid_26">
  <div class="grid_7 alpha">
   <a href={% if sistem.sema %}"{{ sistem.sema.url }}" class="tek_resim"{% else %}"#" style="cursor:default;" onclick="return false;"{% endif %}><div class="systems systems-{{ sistem.resim.filename_root }}_sistem_ufak-{{ sistem.resim.extension|cut:'.' }}"></div></a>
  </div>
  <div class="grid_18 omega">
   {{ sistem.aciklama }}
  </div>
 </div>
 <div class='grid_26 topd'></div>
 {% endfor %}
</div>

urun/templates/sistem_liste_urun.html
{% load fb_versions %}
{% if urun.sistem.all %}
<div class="grid_{{ sira_grid }}">
 <div class="grid_{{ sira_grid }} sprites sprites-{% if sira == 2 %}yarim{% else %}tam{% endif %}_ust-png"></div>
 <div class="grid_{{ sira_grid }} {% if sira == 1 %}one{% else %}two{% endif%}">
  <div class='grid_{{ sira_grid }} topd'></div>
  <div class="grid_{{ sira_grid_inner }} push_{{ sira_grid_push }}">
   <div class="grid_{{ sira_grid_inner }} centered">
    <strong>Bu Ürünü Kullanabileceğiniz Sistemler</strong>
   </div>
   {% for sistem in urun.sistem.all %}
   <div class="grid_{{ sira_grid_inner }} topd"></div>
   <div class="grid_{{ grid_sira_grid_inner }}">
    <div class="grid_7 alpha">
     <a href={% if sistem.sema %}"{{ sistem.sema.url }}" class="tek_resim"{% else %}"#" style="cursor:default;" onclick="return false;"{% endif %}><div class="systems systems-{{ sistem.resim.filename_root }}_sistem_ufak-{{ sistem.resim.extension|cut:'.' }}"></div></a>
    </div>
    <div class="grid_{{ tanitim_grid }} omega">{{ sistem.aciklama }}</div>
   </div>
   {% endfor %}
  </div>
 </div>
 <div class="grid_{{ sira_grid }} sprites sprites-{% if sira == 2 %}yarim{% else %}tam{% endif %}_alt-png"></div>
</div>
{% endif %}

urun/templates/urun.html
{% extends 'taban.html' %}
{% load fb_versions %}
{% load truncate %}

{% block baslik %}{{ urun.isim }}, {{ urun.kategori.isim|title}} - Audio Elektronik{% endblock %}
{% block aciklama %}{{ urun.isim|title }}, {{ urun.kategori.isim|title }}. {{ urun.ozellik.all|join:', '|chars:120 }}{% endblock %}

{% block icerik %}
{% include 'tekli_ac.html' %}
 <div class="grid_53 push_2">
  {% if urun.seri %}
  <img style="float:left;" src="{{ STATIC_CODE }}resim/{{ urun.seri }}.jpg" />
  {% endif %}
  <h2 style='margin-bottom:0px;'>{{ urun.isim }}</h3>
 </div>
 <div class="grid_27 push_1 alpha">
  <div class="grid_27 centered">
   <a href={% version urun.resim.path 'limit' %} class="tek_resim"><img src="{% version urun.resim.path 'urun' %}"/></a>
  </div>
  <div class='grid_26' style='text-align:right'>
   {{ urun.resim_yazi }}
  </div>
  {% if urun.digermodel_set.all %}
  <div class='grid_27 push_1'><strong>Diğer Modeller</strong></div>
  <div class='grid_27'>
   {% for u in urun.digermodel_set.all %}
   <div class='grid_9'>
   <div class='grid_9 topd'></div>
    <div class='grid_9 centered'>
     <a href={% version u.resim.path 'limit' %} class="tek_resim"><img src='{% version u.resim.path 'diger_model' %}'/></a>
    </div>
    <div class='grid_8' style='text-align:right;'>
     {{ u.aciklama }}
    </div>   
   </div>
   {% endfor %}
  </div>
  {% endif %}
 </div>
 <div class="grid_23 push_1"> 
  <div class="grid_23">
   <div class="grid_23">
    <strong>Ürün Özellikleri</strong>
   </div>
   <div class="grid_23 topd"></div>
   {% for ozellik in urun.ozellik.all %}
   <div class="grid_23">- {{ ozellik.isim }}</div>
   {% endfor %}
  </div>
  <div class="grid_22" style='margin-top:10px;'>
   <div class="grid_22 topd"></div>
    {% autoescape off %}
    {{ urun.tanitim }}
    {% endautoescape %}
  </div>
 </div>
   
 <div class="grid_4 push_1 omega">
  {% for d in dokuman %}
  <div class="grid_4 centered" style='margin-top:10px;'>
   <div class="grid_4">
    <a href='/dokuman/{{ d.slug }}'><img src="{% version d.resim.path 'dokuman_ufak' %}"/></a>
   </div>
   <div class="grid_4">
    <a class='sade_link' href='/dokuman/{{ d.slug }}'>{{ d.isim }}</a>
   </div>
  </div>
  <div class='grid_4'style='height:10px;'></div>
  {% endfor %}

  <div class="grid_4 centered" style='margin-top:10px;'>
   <div class="grid_4" style="border: solid 1px; padding-bottom: 2px;">
    <a style="color:#12C;" href="/baglanti-semalari/">Bağlantı Şemaları</a>
   </div>
  </div>
 </div>
{% include 'tekli_kapat.html' %}

{% if panelKonsept or panelBasic %}
{% include 'sistem_liste_urun.html' with sira=2 sira_grid=28 sira_grid_inner=25 sira_grid_push=2 tanitim_grid=18 %}
{% if panelKonsept or panelBasic %}
 {% include 'ikili_ac.html' %}
  <div class="grid_28 topd"></div>
  <div class="grid_28 centered"><strong>Bu Ürün İle Kullanabileceğiniz Paneller</strong></div>
  <div class="grid_28 topd"></div>
  <div class="grid_24 {% if panelKonsept and panelBasic %}push_2{% else %}push_7{% endif %} ">
   {% if panelKonsept %}
   {% include 'panel_liste.html' with seri='konsept' panel=panelKonsept %}
   {% endif %}
   {% if panelBasic %}
   {% include 'panel_liste.html' with seri='basic' panel=panelBasic %}
   {% endif %}
   <div class='grid_24 alpha omega' style='height:20px'></div>
  </div>
 {% include 'ikili_kapat.html' %}
{% endif %}
<div class="clear"></div>
{% else %}
{% include 'sistem_liste_urun.html' with sira=1 sira_grid=56 sira_grid_inner=40 sira_grid_push=8 tanitim_grid=33 %}
<div class="clear"></div>
{% endif %}

{% endblock %}